import type { Auction } from "./types";

export const auctions: Auction[] = [
  {
    id: "OJ-2401",
    image: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85",
    title: "2018 Toyota Camry XSE",
    subtitle: "Foreign used / Automatic / 82,400 km",
    location: "Ikeja, Lagos",
    organiser: "Northstar Auto Exchange",
    status: "Closing soon",
    endsIn: "2 hours 18 minutes",
    sealedOfferCount: 18,
    category: "Cars",
    openingBidNaira: 18_500_000,
    bidIncrementNaira: 50_000,
    inspectionSummary: "VIN and customs papers reviewed. Exterior, cabin and drive-train inspection report available to approved dealers.",
  },
  {
    id: "OJ-2398",
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=85",
    title: "2020 Lexus RX 350",
    subtitle: "Foreign used / AWD / 56,100 km",
    location: "Gwarinpa, Abuja",
    organiser: "Capital Motor Lots",
    status: "Open",
    endsIn: "6 hours 42 minutes",
    sealedOfferCount: 31,
    category: "Cars",
    openingBidNaira: 39_000_000,
    bidIncrementNaira: 100_000,
    inspectionSummary: "Documents, chassis condition and engine scan reviewed. Full report is released after dealer approval.",
  },
  {
    id: "OJ-2404",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85",
    title: "2022 Honda CB500X",
    subtitle: "Foreign used / 471 cc / 9,800 km",
    location: "Apapa, Lagos",
    organiser: "Westline Mobility",
    status: "Open",
    endsIn: "1 day 4 hours",
    sealedOfferCount: 12,
    category: "Motorcycles",
    openingBidNaira: 8_400_000,
    bidIncrementNaira: 25_000,
    inspectionSummary: "Frame, engine and import documents reviewed. Inspection appointment available before the auction closes.",
  },
  {
    id: "OJ-2387",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85",
    title: "2017 Ford Ranger XLT",
    subtitle: "Locally used / 4x4 / Full service history",
    location: "Airport Road, Abuja",
    organiser: "Niger Auto Wholesale",
    status: "Opening soon",
    endsIn: "Registration opens tomorrow",
    sealedOfferCount: 0,
    category: "Trucks",
    openingBidNaira: 21_000_000,
    bidIncrementNaira: 100_000,
    inspectionSummary: "Service records and ownership documents are queued for dealer review before bidding opens.",
  },
];
