import type { Auction } from "./types";

export const auctions: Auction[] = [
  {
    id: "OJ-2401",
    image: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=85",
    title: "2018 Toyota Camry XSE",
    subtitle: "Foreign used · Automatic · 82,400 km",
    location: "Lagos · Ikeja yard",
    organiser: "Northstar Auto Exchange",
    status: "Closing soon",
    endsIn: "02h 18m",
    bids: 18,
    watchers: 42,
    category: "Cars",
    verified: true,
    yourStatus: "Bidding",
    signal: "Your bid is sealed",
  },
  {
    id: "OJ-2398",
    image: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=85",
    title: "2020 Lexus RX 350",
    subtitle: "Foreign used · AWD · 56,100 km",
    location: "Abuja · Gwarinpa yard",
    organiser: "Capital Motor Lots",
    status: "Live now",
    endsIn: "06h 42m",
    bids: 31,
    watchers: 67,
    category: "Cars",
    verified: true,
    yourStatus: "Watching",
    signal: "Your bid stays private",
  },
  {
    id: "OJ-2404",
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85",
    title: "2022 Honda CB500X",
    subtitle: "Foreign used · 471 cc · 9,800 km",
    location: "Lagos · Apapa depot",
    organiser: "Westline Mobility",
    status: "Live now",
    endsIn: "1d 04h",
    bids: 12,
    watchers: 29,
    category: "Motorcycles",
    verified: true,
    yourStatus: "Not joined",
    signal: "Be first to bid privately",
  },
  {
    id: "OJ-2387",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85",
    title: "2017 Ford Ranger XLT",
    subtitle: "Locally used · 4x4 · Full service history",
    location: "Abuja · Airport road",
    organiser: "Niger Auto Wholesale",
    status: "Upcoming",
    endsIn: "Starts tomorrow",
    bids: 0,
    watchers: 15,
    category: "Trucks",
    verified: true,
    yourStatus: "Not joined",
    signal: "Registration opens soon",
  },
];

export const activity = [
  { title: "Bid sealed", detail: "Toyota Camry XSE · OJ-2401", time: "12 min ago", tone: "green" },
  { title: "Inspection report viewed", detail: "Lexus RX 350 · OJ-2398", time: "Yesterday", tone: "blue" },
  { title: "Joined auction", detail: "Honda CB500X · OJ-2404", time: "2 days ago", tone: "amber" },
];
