import type { Auction } from "./types";

export const auctions: Auction[] = [
  {
    id: "OJ-2401",
    images: [
      {
        url: "https://www.cstatic-images.com/stock/1000x1000/78/img-954647238-1497975313078.JPG",
        alt: "2018 Toyota Camry XSE in dark blue, front three-quarter view",
        sourceLabel: "Cars.com 2018 Camry XSE gallery",
        sourceUrl: "https://www.cars.com/articles/2018-toyota-camry-review-exterior-photo-gallery-1420695851030/",
      },
      {
        url: "https://cdn.motor1.com/images/mgl/xVNVy/s1/2018-toyota-camry-xse-review.jpg",
        alt: "2018 Toyota Camry XSE in red, rear three-quarter view",
        sourceLabel: "Motor1 2018 Camry XSE review",
        sourceUrl: "https://www.motor1.com/reviews/238784/2018-toyota-camry-xse-star-rating/",
      },
    ],
    title: "2018 Toyota Camry XSE",
    subtitle: "Foreign used / Automatic / 82,400 km",
    location: "Ikeja, Lagos",
    organiser: "Northstar Auto Exchange",
    status: "Closing soon",
    endsIn: "2 hours 18 minutes",
    sealedOfferCount: 18,
    category: "Cars",
    openingBidNaira: 18_500_000,
    bidIncrementNaira: 50_000,
    inspectionSummary: "VIN, customs record, exterior, cabin and drive-train checks are recorded for verified dealers.",
    vehicleDetails: [
      { label: "Lot number", value: "OJ-2401" },
      { label: "Odometer", value: "82,400 km" },
      { label: "Engine", value: "3.5L petrol" },
      { label: "Transmission", value: "8-speed automatic" },
      { label: "Drive", value: "Front-wheel drive" },
      { label: "Keys", value: "2 reported" },
    ],
    conditionHighlights: ["Exterior walk-around recorded", "Cabin controls checked", "Engine and drive test recorded"],
    documents: [
      { name: "VIN and customs pack", access: "Verified dealer access" },
      { name: "Inspection summary", access: "Available now" },
      { name: "Collection release", access: "After cleared payment" },
    ],
    collectionWindow: "Collection is scheduled within 72 hours after cleared payment.",
  },
  {
    id: "OJ-2398",
    images: [
      {
        url: "https://dealerimages.dealereprocess.com/image/upload/1921855.jpg",
        alt: "2020 Lexus RX 350 in grey, side profile on a city street",
        sourceLabel: "Lexus RX 350 reference image",
        sourceUrl: "https://www.lexusofhighlandpark.com/cc-2020-lexus-rx-350-financing-near-lake-villa-il/",
      },
      {
        url: "https://dealerimages.dealereprocess.com/image/upload/2129059.jpg",
        alt: "2020 Lexus RX 350 in silver, side profile",
        sourceLabel: "Lexus RX 350 reference image",
        sourceUrl: "https://www.lexusofmerrillville.com/cc-2020-lexus-rx-350-vs-2020-acura-rdx-near-schererville-in/",
      },
    ],
    title: "2020 Lexus RX 350",
    subtitle: "Foreign used / AWD / 56,100 km",
    location: "Gwarinpa, Abuja",
    organiser: "Capital Motor Lots",
    status: "Open",
    endsIn: "6 hours 42 minutes",
    sealedOfferCount: 31,
    category: "Cars",
    openingBidNaira: 39_000_000,
    bidIncrementNaira: 100_000,
    inspectionSummary: "Documents, chassis condition, tyre wear and engine scan have been recorded for dealer review.",
    vehicleDetails: [
      { label: "Lot number", value: "OJ-2398" },
      { label: "Odometer", value: "56,100 km" },
      { label: "Engine", value: "3.5L V6 petrol" },
      { label: "Transmission", value: "8-speed automatic" },
      { label: "Drive", value: "All-wheel drive" },
      { label: "Keys", value: "2 reported" },
    ],
    conditionHighlights: ["Chassis visual check recorded", "Diagnostic scan attached", "Tyre condition noted in report"],
    documents: [
      { name: "Import and ownership pack", access: "Verified dealer access" },
      { name: "Condition report", access: "Available now" },
      { name: "Engine scan extract", access: "Available now" },
    ],
    collectionWindow: "Collection is scheduled within 48 hours after cleared payment.",
  },
  {
    id: "OJ-2404",
    images: [
      {
        url: "https://ultimatemotorcycling.com/wp-content/uploads/2022/06/2022-honda-cb500x-review-adventure-motorcycle-9.jpg",
        alt: "2022 Honda CB500X in green and black, side profile",
        sourceLabel: "Ultimate Motorcycling CB500X review",
        sourceUrl: "https://ultimatemotorcycling.com/2022/06/03/2022-honda-cb500x-review-16-fast-facts-adventure-motorcycle/",
      },
      {
        url: "https://www.bikeit.gr/media/k2/galleries/28090/honda-cb500x-2022-dt--00006.jpg",
        alt: "2022 Honda CB500X adventure motorcycle on a road",
        sourceLabel: "BikeIt 2022 CB500X press gallery",
        sourceUrl: "https://www.bikeit.gr/nea-montela-honda/item/28090-honda-cb500x-2022-to-analytiko-deltio-typou-techika-charaktiristika-kai-timi",
      },
    ],
    title: "2022 Honda CB500X",
    subtitle: "Foreign used / 471 cc / 9,800 km",
    location: "Apapa, Lagos",
    organiser: "Westline Mobility",
    status: "Open",
    endsIn: "1 day 4 hours",
    sealedOfferCount: 12,
    category: "Motorcycles",
    openingBidNaira: 8_400_000,
    bidIncrementNaira: 25_000,
    inspectionSummary: "Frame, engine, brakes and import records were inspected before this dealer auction.",
    vehicleDetails: [
      { label: "Lot number", value: "OJ-2404" },
      { label: "Odometer", value: "9,800 km" },
      { label: "Engine", value: "471 cc parallel twin" },
      { label: "Transmission", value: "6-speed manual" },
      { label: "Type", value: "Adventure motorcycle" },
      { label: "Keys", value: "2 reported" },
    ],
    conditionHighlights: ["Frame visual check recorded", "Front and rear brake check recorded", "Import documentation reviewed"],
    documents: [
      { name: "Import pack", access: "Verified dealer access" },
      { name: "Mechanical summary", access: "Available now" },
      { name: "Collection release", access: "After cleared payment" },
    ],
    collectionWindow: "Collection is scheduled within 72 hours after cleared payment.",
  },
  {
    id: "OJ-2387",
    images: [
      {
        url: "https://assets.shannons.com.au/Z7AUWU196W5DV18D/O15F3QAB4C1B506F/huikn7tvjzooy05f-30fo9fwh6zwz7qna/jpg/2400x1800x3/vehicle/2017-ford-ranger-xlt-4x4.jpg",
        alt: "2017 Ford Ranger XLT 4x4 in dark grey, front three-quarter view",
        sourceLabel: "Shannons Club 2017 Ranger XLT 4x4",
        sourceUrl: "https://club.shannons.com.au/club/enthusiasts/mattthewlis27/garage/2017-ford-ranger-xlt-4x4/",
      },
      {
        url: "https://images.carexpert.com.au/resize/1400/-/vehicles/source-j/j/o/jjo5fswf20160909.jpg",
        alt: "2017 Ford Ranger XLT double-cab pickup in blue",
        sourceLabel: "CarExpert 2017 Ranger XLT reference",
        sourceUrl: "https://www.carexpert.com.au/ford/ranger/2017-xlt-jjo5fswf20160909",
      },
    ],
    title: "2017 Ford Ranger XLT",
    subtitle: "Locally used / 4x4 / Full service history",
    location: "Airport Road, Abuja",
    organiser: "Niger Auto Wholesale",
    status: "Opening soon",
    endsIn: "Registration opens tomorrow",
    sealedOfferCount: 0,
    category: "Trucks",
    openingBidNaira: 21_000_000,
    bidIncrementNaira: 100_000,
    inspectionSummary: "Service records, ownership documents and a pre-sale inspection are queued for dealer review.",
    vehicleDetails: [
      { label: "Lot number", value: "OJ-2387" },
      { label: "Service history", value: "Reported complete" },
      { label: "Engine", value: "3.2L turbo diesel" },
      { label: "Transmission", value: "6-speed automatic" },
      { label: "Drive", value: "4x4" },
      { label: "Keys", value: "2 reported" },
    ],
    conditionHighlights: ["Service history queued", "Ownership documentation queued", "Pre-sale inspection appointment planned"],
    documents: [
      { name: "Service records", access: "Released at registration" },
      { name: "Ownership pack", access: "Released at registration" },
      { name: "Condition report", access: "Released before opening" },
    ],
    collectionWindow: "Collection terms will be confirmed when the lot opens.",
  },
];
